[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_pay = "6U98LYTqD2ebB3eJyb5ww9kkna9N9M27wszB9rvd6z1r"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "devnet"
cluster = "https://rpc-mainnet-fork.epochs.studio"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
