[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_pay = "HSSp1Se1k21b27EepLuKEXfntvtMZyJ4LK761GLanFLr"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "devnet"
cluster = "https://rpc-mainnet-fork.epochs.studio"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
