[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_pay = "9PCD9v9qBCi5t9fKDc2LqiXtsjjQVKizQc4KQG3yEYdh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/akirawu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
